version: "3.5"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USERNAME=bookstack
      - DB_PASSWORD=tmpmysql
      - DB_DATABASE=bookstackapp
    volumes:
      - ./config-wiki:/config
      - ./themes:/var/www/html/themes
      - ./custom:/var/www/html/public/custom
    ports:
      - 7000:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=tmpmysql
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=tmpmysql
    volumes:
      - ./config-db:/config
    restart: unless-stopped
    ports:
      - 3306:3306
